// <auto-generated />
namespace iTechArt.Labs.iTechArtSurvey.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpdateQuestionToReferenceOnSurveyPage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateQuestionToReferenceOnSurveyPage));
        
        string IMigrationMetadata.Id
        {
            get { return "201708040858160_UpdateQuestionToReferenceOnSurveyPage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
