export const SET_FILTER_STRING = 'SET_FILTER_STRING';
export const DELETE_ITEM = 'DELETE_ITEM';
export const GET_ITEM = 'GET_ITEM';
export const SET_MANAGE_MODE = 'SET_MANAGE_MODE';
export const GET_ITEMS_DESCRIPTION = 'GET_ITEMS_DESCRIPTION';
export const CLEAR_CURRENT_ITEM = 'CLEAR_CURRENT_ITEM';
export const SAVE_QUESTION = 'SAVE_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const ADD_QUESTION = 'ADD_QUESTION';

